FROM rust:slim-bookworm AS chef
RUN apt update && apt install -y wget software-properties-common gnupg sudo
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor -o /usr/share/keyrings/llvm-snapshot.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-18 main" | tee /etc/apt/sources.list.d/llvm-toolchain-18.list
RUN apt update && apt install -y clang-18 lld-18 clangd-18 libclang-18-dev lld pkg-config curl tar && cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
ARG MINIFI_SDK_PATH
ENV MINIFI_SDK_PATH=${MINIFI_SDK_PATH}

COPY --from=planner /app/recipe.json recipe.json

# Conditionally copy the local SDK files from the target directory
COPY target/.docker_sd[k] /app/target/.docker_sdk/
COPY target/.docker_sdk.zi[p] /app/target/

RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release

# Export Stage
FROM scratch AS bin-export
COPY --from=builder /app/target/release/libminifi_rs_playground.so /
COPY --from=builder /app/target/release/libminifi_tensor.so /
